### ISSUE TITLE
Extremely slow evaluation

### ISSUE THREAD

**Issue by berendbaas** [LightTable/Clojure#39]
Hi folks,
I don't know if any other users are experiencing this issue, but evaluating in the instarepl is extremely slow for me and seems to freeze up the editor for 5+ seconds on pretty much every change. It can happen for every small edit which triggers the instarepl to evaluate, which basically hangs the editor until the evaluation results come back. Now, I've not been able to look at the source code to see if I can determine the cause of this issue, but to me, it would seem to be some kind of blocking IO issue. The behaviour is as if the IO thread halts until the REPL response comes back and only then allows new commands to be executed. This makes the responsiveness of the app incredibly sluggish of course, whenever the IO response takes long.

Is this per chance what the ";;TODO: version out of sync" is for in https://github.com/LightTable/Clojure/blob/master/src/lt/plugins/clojure/instarepl.cljs ?

Info: 
Macbook Pro 2012
quad core 2.4Ghz i7, 
16GB Ram 
Mac OS X Yosemite
Light table 0.7.2 (Binary 0.8.4)
Clojure plugin 0.1.1

**Comment by cldwalker** [comment]
Hi. This is most likely a result of yosemite and the node-webkit version we use - see #1685. We're switching to atom-shell and once that is release that should resolve the sluggishness

**Comment by cldwalker** [comment]
Closing as this is fairly out of date. Feel free to install the latest LightTable, Clojure plugin, ClojureInstarepl plugin and if there's an issue open one at https://github.com/LightTable/ClojureInstarepl/issues
