### ISSUE TITLE
Intercepting the connection between lighttable and nrepl

### ISSUE THREAD

**Issue by Foxboron** [LightTable/Clojure#46]
Currently working on a nREPL for hylang (https://github.com/hy/hylang), and we thought it would be neat to try and fake our way through a bunch of nrepl clients, like cider and fireplace, to just see how well this works.

I'm however having a little problem with lighttable. There does not seem to be any response after the final response, and i'm wondering if anyone could intercept a connection between lighttable and lein-light-nrepl.

The project:
https://github.com/Foxboron/HyREPL

```
in: {'op': 'clone'}

out: {'session': '81a5fae6-08e4-425f-ac9b-aea23b6d8a6d', 'status': ['done'], 'id': None, 'new-session': '206dec4a-01b1-46a4-803a-12d66c314629'}

in: {'data': '{:settings {:name "localhost:1337", :remote true, :client-id 76}}', 'id': 76, 'session': '206dec4a-01b1-46a4-803a-12d66c314629', 'op': 'client.init'}

out: {'encoding': 'edn', 'session': '81a5fae6-08e4-425f-ac9b-aea23b6d8a6d', 'status': ['done'], 'id': 76, 'data': '{:remote true, :client-id 76, :name "localhost:1337", :dir "/home/fox/github/hyrepl", :type "lein-light-nrepl", :commands [:editor.eval.clj :editor.clj.doc :editor.cljs.doc :editor.clj.hints :editor.cljs.hints :docs.clj.search :docs.cljs.search :editor.eval.clj.sonar :editor.eval.clj.cancel :editor.eval.cljs :cljs.compile]}', 'op': 'client.settings'}
```

**Comment by kenny-evitt** [comment]
@Foxboron I have only the vaguest idea of what you're doing, but it seems very interesting. It may be a (long) while before anyone else comments on this issue as we're having some trouble keeping the core Light Table project going.

If you would, please add enough (detailed) info so that someone could easily reproduce the problem you're having. As-is, I don't understand how (or *whether*) you're using HyREPL with Light Table.

**Comment by Foxboron** [comment]
@kenny-evitt essentially. Its not really a LightTable problem. It's just me and a guy trying to mock our way to use this plugin. Its just a hacky project.

Essentially, what i want is the communication between lighttable and lein-light-nrepl when they initialize the session, to see why lighttable does not respond to us.

**Comment by kenny-evitt** [comment]
@Foxboron [the Light Table Google Groups group](https://groups.google.com/forum/#!forum/light-table-discussion) might be a better venue for your questions then.
