### ISSUE TITLE
Clojure remote connect is not working.

### ISSUE THREAD

**Issue by gfZeng** [LightTable/Clojure#63]
[google group discussion here](https://groups.google.com/forum/#!topic/light-table-discussion/sS3gWzVgMZk)

Like the discussion. 
I use `boot repl` launch a repl, and then connect it. It's ok, the connection is successful.
but when I try to `eval line(cmd+enter)`, the light table try make a new connection
instead of use the exists connection. And the new connection failed after a minute.

I used `jps -m` show the new connection info:
> lein-light-standalone.jar LightTable-REPL

**Comment by kenny-evitt** [comment]
The original entry from the forum post:

> I following [this instructions](https://github.com/boot-clj/boot/wiki/Light-Table-REPL) success connected to repl.

> but, when I try to eval line(cmd+enter), light table try to connect a new repl, and finally failed.

> why light table can not use the connected repl.

**Comment by kenny-evitt** [comment]
@gfZeng [Here's an entry ](http://hoplon.discoursehosting.net/t/connecting-to-a-hoplon-boot-nrepl-e-g-with-lighttable/97/7) from the Boot (Hoplon) forum for a thread titled "Connecting to a Hoplon/Boot nREPL (e.g. with Lighttable)" that looks like it might have some relevant info.

**Comment by gfZeng** [comment]
@kenny-evitt 
not the same problem. 
my problem the remote connected repl not used when I tried to eval code. the light table try to make an new connection.

**Comment by kenny-evitt** [comment]
@gfZeng Can you select the nREPL connection before evaling the code?

**Comment by gfZeng** [comment]
@kenny-evitt 

How can I select connection

**Comment by kenny-evitt** [comment]
In the command pane, run the command "Connect: Add Connection". Or run the command "Connect: Show connect bar" to see any existing connections.

**Comment by gfZeng** [comment]
@kenny-evitt 

Yes, I saw it surely.

![image](https://cloud.githubusercontent.com/assets/4434624/12191104/5793d9d8-b60b-11e5-98d1-1733251ef646.png)

**Comment by kenny-evitt** [comment]
@gfZeng Does connecting to the existing connection fix this?

**Comment by gfZeng** [comment]
@kenny-evitt 
I did not found an option or command that can do this action --- connecting to the existing connection

**Comment by kenny-evitt** [comment]
@gfZeng I guess you can't connect to the existing connection; I'm not sure why. Would you mind sharing your project, or a minimal example [this would be preferred], and maybe expand on what you're doing that you described as:

> I use `boot repl` launch a repl, and then connect it.

Running `boot repl` is clear but what steps, exactly, are you doing to connect to it in Light Table?

I found [this example Clojure Boot project](https://github.com/adzerk-oss/boot-cljs-example) – would you try to reproduce your problem using that project and let me know whether you can? If you can reproduce it with the example, I'll use that to investigate further.
