### ISSUE TITLE
Indentation changes for Clojure mode

### ISSUE THREAD

**Issue by cldwalker** [LightTable/Clojure#67]
From https://github.com/LightTable/LightTable/issues/1782:

I've noticed that Clojure code gets indented in LT the same way it's indented (or was) by Emacs's clojure-mode. Unfortunately some of the indentation stuff you copied were actually bugs in clojure-mode (that were recently fixed in version 4.0) - like the indentation of `cond` (which should use 2 spaces) and threading forms, which should be indented like:

```
(-> a
  b
  c)
```

instead of:

```
(-> a
    b
    c)
```

**Comment by cldwalker** [comment]
As discussed [here](https://github.com/LightTable/LightTable/issues/1782#issuecomment-66918814), blocked by #26

**Comment by carocad** [comment]
#26 is already closed. should this still be opened or blocked at all?

**Comment by kenny-evitt** [comment]
@bbatsov Please comment if this should still be open.
