### ISSUE TITLE
dosync is not indented like do

### ISSUE THREAD

**Issue by muhuk** [LightTable/Clojure#69]
`do` is indented like this:

```clojure
(do
  (foo)
  (bar))
```

But `dosync` is indented like a regular/unknown function:

```clojure
(dosync
 (foo)
 (bar))
```

-----

Light Table version 0.8.0, Clojure plugin version 0.3.0

**Comment by cldwalker** [comment]
Hi. Thanks for the report. This seems to be working fine [upstream](http://codemirror.com/mode/clojure/). Once we knock out #26, we should be able to pull in CodeMirror's latest mode and this should be fixed

**Comment by muhuk** [comment]
Thanks for the info @cldwalker

**Comment by cldwalker** [comment]
Closing as 0.3.1 Clojure has fixed this
